[package]
name = "packageurl"
version = "0.2.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
license = "MIT"
description = "Rust implementation of the package url specification"
documentation = "https://docs.rs/packageurl"
repository = "https://github.com/althonos/packageurl-rs"
readme = "README.md"
keywords = ["purl", "package-url"]
categories = ["parser-implementations", "encoding", "development-tools"]

[dependencies]
percent-encoding = "^1.0.0"
error-chain = "^0.7.1"
memchr = { version = "^2.0.0", optional = true}

[dev-dependencies]
serde = "^1.0.37"
serde_derive = "^1.0.37"
serde_json = "^1.0.13"
lazy_static = "^1.0.0"
url = "^1.7.0"

[badges]
travis-ci   = { repository = "althonos/packageurl-rs" }
codecov     = { repository = "althonos/packageurl-rs" }
maintenance = { status = "actively-developed" }
